# Generated by Django 3.2 on 2023-05-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230511_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='pipeline_version_id',
            field=models.UUIDField(default='eed9e625-1d4c-483a-dd8f-2d6b58e0a3ed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runrequest',
            name='pipeline_version_name',
            field=models.TextField(default='eed9e625-1d4c-483a-dd8f-2d6b58e0a3ed'),
            preserve_default=False,
        ),
    ]
