# Generated by Django 3.2 on 2023-05-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230511_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runrequest',
            name='user_id',
        ),
    ]
