# Generated by Django 3.2 on 2025-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_datasetrequest_response_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='pipeline_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
