# Generated by Django 3.2 on 2025-05-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20250510_1932'),
        ('app', '0009_runrequest_pipeline_params'),
    ]

    operations = [
    ]
